app = "salvacao-bot"
primary_region = "fra"

[build]

[[processes]]
  name = "bot"
  cmd = "python main.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
