-- Add visual_features JSONB column to cases to support future ML-inferred trait tagging (WP2/WP4).
-- Example payload: {"ears": "pointy", "coat": "short", "size_inferred": "medium", "tail": "curled"}
ALTER TABLE cases ADD COLUMN IF NOT EXISTS visual_features jsonb DEFAULT '{}'::jsonb;
COMMENT ON COLUMN cases.visual_features IS 'Inferred visual traits (ears, coat, tail) generated by ML pipeline for faceted search.';

-- Add index to support fast JSONB querying (e.g., visual_features->>'ears' = 'pointy')
CREATE INDEX IF NOT EXISTS cases_visual_features_idx ON cases USING gin (visual_features);
